-- Migración 2026-08-28 — Noticias iniciales (7 notas de prensa) con imagen placeholder. Idempotente por slug.
INSERT INTO media (nombre_archivo, nombre_original, ruta, tipo, mime_type, tamano_bytes, ancho, alto, alt_text)
SELECT * FROM (SELECT 'noticia-placeholder.svg' AS na, 'noticia-placeholder.svg' AS no, 'assets/img/noticia-placeholder.svg' AS ruta, 'imagen' AS tipo, 'image/svg+xml' AS mime, 0 AS tam, 1200 AS an, 675 AS al, 'Valores Casa de Bolsa — Noticias' AS alt) AS t
WHERE NOT EXISTS (SELECT 1 FROM media WHERE ruta = 'assets/img/noticia-placeholder.svg');

INSERT INTO noticias (titulo, slug, resumen, contenido, imagen_destacada_id, categoria, estado, visible_front, fecha_publicacion, autor)
SELECT 'Christian Borja proyecta mayor inversión extranjera en Paraguay por su estabilidad económica', 'christian-borja-proyecta-mayor-inversion-extranjera-en-paraguay-por-su-estabilidad-economica', 'En una entrevista publicada por Revista Plus, el CEO de Valores Casa de Bolsa repasó el desempeño de la firma en 2023 y su expansión hacia bienes raíces y tecnología.', '<p><em>Fuente: Revista Plus, 16 de enero de 2024</em></p>
<p>Christian Borja, CEO de Valores Casa de Bolsa, evaluó en una entrevista con Revista Plus el desempeño de la compañía durante 2023 y sus perspectivas para el año siguiente. Según el ejecutivo, la casa de bolsa se ubicó entre las cinco firmas con mayor volumen de operaciones en renta fija del país sin pertenecer a un grupo bancario, y mantuvo el liderazgo en el mercado de renta variable.</p>
<p>Borja detalló que la compañía impulsó dos nuevas unidades de negocio: Valores Real Estate, dedicada al desarrollo inmobiliario con cerca de USD 30 millones en activos disponibles en los departamentos de Central, Alto Paraná e Itapúa, y Valores Innovations, orientada a tecnología, educación y salud.</p>
<p>Sobre el contexto macroeconómico, el ejecutivo proyectó una mayor entrada de inversión extranjera directa e indirecta en 2024, atribuible, dijo, a “su manejo macro de la economía y a la proximidad al grado de inversión”. Mencionó además expectativas positivas para el sector agrícola, el avance de proyectos de infraestructura como el aeropuerto, la red vial y el dragado fluvial, y una eventual reducción de tasas de interés.</p>
<p>En cuanto al desarrollo del mercado bursátil, Borja señaló que “el Estado y la Superintendencia de Valores tendrán un rol fundamental, ya que la legislación debe permitir que inversionistas no domiciliados en el país puedan invertir en papeles emitidos por Paraguay en nuestra bolsa”. Agregó: “Sueño con que Paraguay logre alcanzar el grado de inversión, con seguridad jurídica que permita la atracción y desembarco de grupos económicos”.</p>
<p>El CEO también se refirió a la digitalización del sector financiero, a la que calificó como “presente, no futuro”, y remarcó la importancia de la inclusión financiera: “Las personas que viven en zonas rurales deben poder invertir tanto como aquellas que viven en las ciudades, mientras estén bancarizados”.</p>
<p>Borja es doctor en Jurisprudencia por la Pontificia Universidad Católica del Ecuador, especialista en Derecho Financiero y Bursátil, y reside en Paraguay desde 2005.</p>
<p><a href="https://revistaplus.com.py/2024/01/16/christian-borja-paraguay-atraera-mas-inversion-extranjera-por-su-estabilidad-economica-y-proximidad-al-grado-de-inversion/" target="_blank" rel="noopener">Nota original →</a></p>', (SELECT id FROM media WHERE ruta = 'assets/img/noticia-placeholder.svg'), 'negocios', 'publicado', 1, '2024-01-16', 'Valores Casa de Bolsa'
WHERE NOT EXISTS (SELECT 1 FROM noticias WHERE slug = 'christian-borja-proyecta-mayor-inversion-extranjera-en-paraguay-por-su-estabilidad-economica');

INSERT INTO noticias (titulo, slug, resumen, contenido, imagen_destacada_id, categoria, estado, visible_front, fecha_publicacion, autor)
SELECT 'Christian Borja: la educación financiera y la especialización, claves para ampliar el mercado de capitales', 'christian-borja-la-educacion-financiera-y-la-especializacion-claves-para-ampliar-el-mercado-de-capitales', 'En una entrevista con Forbes Paraguay, el presidente de Valores Casa de Bolsa analizó los desafíos para incrementar la participación de inversores y pymes en la bolsa local.', '<p><em>Fuente: Forbes Paraguay, 19 de septiembre de 2024</em></p>
<p>En una entrevista publicada por Forbes Paraguay, Christian Borja, presidente de Valores Casa de Bolsa, planteó que ampliar la participación en el mercado de capitales paraguayo requiere un trabajo conjunto entre el sector privado y el Estado. “La inversión es el ahorro que se ha destinado para que crezca el dinero”, explicó, y consideró necesario reforzar la educación financiera desde colegios y universidades.</p>
<p>El ejecutivo detalló que las casas de bolsa vienen recurriendo a charlas, marketing en redes sociales, podcasts y programas de educación institucional para acercar al público general al funcionamiento de la bolsa de valores.</p>
<p>Sobre la atracción de nuevas empresas emisoras, Borja sostuvo que difundir casos de compañías que ya captaron fondos en el mercado puede motivar a otras a seguir ese camino, y destacó el rol que pueden cumplir los gremios empresariales —de construcción, industria y el sector farmacéutico, entre otros— para promover estas alternativas de financiamiento entre sus asociados.</p>
<p>El presidente de Valores Casa de Bolsa identificó además un desafío puntual en el segmento de pequeñas y medianas empresas, que enfrentan obstáculos administrativos para acceder al mercado bursátil. En ese sentido, señaló la necesidad de políticas estatales y regulaciones más ágiles que faciliten su ingreso.</p>
<p><a href="https://www.forbes.com.py/especiales/evolucion-rapida-empuja-especializacion-n58799" target="_blank" rel="noopener">Nota original →</a></p>', (SELECT id FROM media WHERE ruta = 'assets/img/noticia-placeholder.svg'), 'mercado', 'publicado', 1, '2024-09-19', 'Valores Casa de Bolsa'
WHERE NOT EXISTS (SELECT 1 FROM noticias WHERE slug = 'christian-borja-la-educacion-financiera-y-la-especializacion-claves-para-ampliar-el-mercado-de-capitales');

INSERT INTO noticias (titulo, slug, resumen, contenido, imagen_destacada_id, categoria, estado, visible_front, fecha_publicacion, autor)
SELECT 'Valores Innovations invierte USD 4,5 millones en centro de simulación médica en Hernandarias', 'valores-innovations-invierte-usd-4-5-millones-en-centro-de-simulacion-medica-en-hernandarias', 'El Grupo Valores, a través de su subsidiaria Valores Innovations, inauguró CESIMED, el primer centro de simulación médica de alta complejidad del país, según publicó ABC Color.', '<p><em>Fuente: ABC Color, 25 de noviembre de 2024</em></p>
<p>Valores Casa de Bolsa, a través de su subsidiaria Valores Innovations, invirtió USD 4.500.000 en la creación del Centro de Simulación Médica, Seguridad del Paciente e Innovación en la Educación (CESIMED), inaugurado en Hernandarias, departamento de Alto Paraná, según informó ABC Color.</p>
<p>El centro está equipado con simuladores de baja, mediana y alta complejidad, e incorpora tecnología de realidad virtual aplicada a procedimientos de endoscopia y cirugía laparoscópica, con el objetivo de desarrollar habilidades clínicas y quirúrgicas en estudiantes de medicina.</p>
<p>CESIMED inició operaciones en diciembre de 2024 con cursos de reválida para profesionales de la salud, con planes de expansión posterior de su oferta académica.</p>
<p>La inversión se enmarca en la estrategia de diversificación de Valores Casa de Bolsa, que en los últimos años amplió su operación más allá del mercado bursátil hacia sectores como el inmobiliario, a través de Valores Real Estate, y ahora la educación médica y la innovación tecnológica.</p>
<p><em>Contenido producido por Brand Lab para Valores Innovations.</em></p>
<p><a href="https://www.abc.com.py/negocios/2024/11/25/simulacion-medica-de-alta-fidelidad-llega-a-hernandarias/" target="_blank" rel="noopener">Nota original →</a></p>', (SELECT id FROM media WHERE ruta = 'assets/img/noticia-placeholder.svg'), 'inversiones', 'publicado', 1, '2024-11-25', 'Valores Casa de Bolsa'
WHERE NOT EXISTS (SELECT 1 FROM noticias WHERE slug = 'valores-innovations-invierte-usd-4-5-millones-en-centro-de-simulacion-medica-en-hernandarias');

INSERT INTO noticias (titulo, slug, resumen, contenido, imagen_destacada_id, categoria, estado, visible_front, fecha_publicacion, autor)
SELECT 'El mercado de capitales paraguayo crece de la mano de la inversión extranjera, pero necesita más empresas locales', 'el-mercado-de-capitales-paraguayo-crece-de-la-mano-de-la-inversion-extranjera-pero-necesita-mas-empresas-locales', 'Christian Borja, CEO de Valores Casa de Bolsa, valoró en Forbes Paraguay el año bursátil 2024 y señaló la falta de protagonismo de las empresas paraguayas como una de las principales asignaturas pendientes.', '<p><em>Fuente: Forbes Paraguay, 31 de diciembre de 2024</em></p>
<p>El mercado de capitales de Paraguay registró avances significativos durante 2024, impulsado por un entorno macroeconómico favorable y por políticas orientadas a atraer inversión internacional, según un balance publicado por Forbes Paraguay con declaraciones de Christian Borja, CEO de Valores Casa de Bolsa.</p>
<p>“El ambiente que existe es muy positivo en cuanto a proyectos, a la calificación que nos dio Moody’s de Grado de Inversión, y lo que se espera hacer con grandes proyectos”, afirmó Borja. Según el ejecutivo, las emisiones del año alcanzaron cerca de USD 6.000 millones, con expectativas de llegar a entre USD 8.000 y USD 10.000 millones en los próximos años.</p>
<p>Borja reconoció, sin embargo, que la recuperación del mercado primario —en particular las emisiones de bonos del Tesoro— enfrentó obstáculos administrativos: “Lastimosamente, por una restricción del Ministerio de Economía, no hemos podido avanzar en este frente como se esperaba”.</p>
<p>El CEO subrayó que uno de los principales desafíos pendientes es lograr que más empresas paraguayas —y no solo inversión extranjera— utilicen la bolsa como fuente de financiamiento. En ese sentido, mencionó que la Administración Nacional de Electricidad (ANDE) evalúa captar financiamiento a través del mercado de capitales, lo que fortalecería sectores como el energético.</p>
<p>Entre las claves para consolidar el crecimiento del mercado, Borja mencionó la diversificación de productos de inversión, la mejora de la infraestructura del país y la oferta de instrumentos de calidad para inversores internacionales.</p>
<p><a href="https://www.forbes.com.py/macroeconomia/el-mercado-capitales-crece-inversiones-extranjeras-pero-necesita-mas-protagonismo-empresas-paraguayas-n64981" target="_blank" rel="noopener">Nota original →</a></p>', (SELECT id FROM media WHERE ruta = 'assets/img/noticia-placeholder.svg'), 'macro', 'publicado', 1, '2024-12-31', 'Valores Casa de Bolsa'
WHERE NOT EXISTS (SELECT 1 FROM noticias WHERE slug = 'el-mercado-de-capitales-paraguayo-crece-de-la-mano-de-la-inversion-extranjera-pero-necesita-mas-empresas-locales');

INSERT INTO noticias (titulo, slug, resumen, contenido, imagen_destacada_id, categoria, estado, visible_front, fecha_publicacion, autor)
SELECT 'Christian Borja: “Necesitamos dos notas más para consolidar el Grado de Inversión”', 'christian-borja-necesitamos-dos-notas-mas-para-consolidar-el-grado-de-inversion', 'En un análisis publicado por Forbes Paraguay, el CEO de Valores Casa de Bolsa repasó los desafíos y oportunidades del mercado de capitales paraguayo de cara a 2025.', '<p><em>Fuente: Forbes Paraguay, 2 de abril de 2025</em></p>
<p>El mercado de valores paraguayo continúa expandiéndose de la mano de la estabilidad macroeconómica y el crecimiento de las operaciones con bonos del Tesoro, según un análisis de Christian Borja, CEO de Valores Casa de Bolsa, publicado por Forbes Paraguay.</p>
<p>“Lo que está sucediendo es que el país crece. Este viene haciendo bien las cosas desde hace muchos años en términos macroeconómicos”, sostuvo Borja, quien señaló que la legislación vigente acompaña ese desarrollo.</p>
<p>El ejecutivo detalló que los bonos del Tesoro representan aproximadamente el 50% del volumen total de operaciones bursátiles del país, y que durante el año el mercado primario fue gestionado por el Banco Central.</p>
<p>Respecto a la calificación crediticia, Borja consideró que Paraguay necesita avanzar en nuevas notas para consolidar el Grado de Inversión: “Necesitamos dos notas más para consolidar el Grado de Inversión. Lo ideal es tener tres, pero si tenemos dos, está perfecto”.</p>
<p>El CEO también se refirió al rol de la confianza y la diversificación de productos como condiciones para profundizar el mercado local: “La confianza y la diversificación son los primeros pasos hacia la profundización que necesitamos”. Sobre los beneficios de cotizar en la bolsa, agregó: “El hecho de estar en la Bolsa también involucra un reconocimiento. Implica que las empresas están haciendo bien las cosas en materia administrativa y económica”.</p>
<p>Borja destacó, además, que cada vez más empresas de otras regiones del país —y no solo de Asunción— recurren a la Bolsa de Valores como alternativa de financiamiento, en lo que consideró una señal de expansión geográfica del mercado.</p>
<p><a href="https://www.forbes.com.py/summit/el-futuro-mercado-capitales-paraguay-desafios-oportunidades-2025-n69971" target="_blank" rel="noopener">Nota original →</a></p>', (SELECT id FROM media WHERE ruta = 'assets/img/noticia-placeholder.svg'), 'summit', 'publicado', 1, '2025-04-02', 'Valores Casa de Bolsa'
WHERE NOT EXISTS (SELECT 1 FROM noticias WHERE slug = 'christian-borja-necesitamos-dos-notas-mas-para-consolidar-el-grado-de-inversion');

INSERT INTO noticias (titulo, slug, resumen, contenido, imagen_destacada_id, categoria, estado, visible_front, fecha_publicacion, autor)
SELECT 'Christian Borja Terán: el Grado de Inversión, “la supercarretera” hacia Paraguay 2.0', 'christian-borja-teran-el-grado-de-inversion-la-supercarretera-hacia-paraguay-2-0', 'En el marco de un Summit organizado por Forbes Paraguay, el presidente de Valores Casa de Bolsa proyectó que la economía paraguaya podría duplicarse en una década de la mano del mercado bursátil.', '<p><em>Fuente: Forbes Paraguay, 20 de diciembre de 2025</em></p>
<p>El mercado de capitales paraguayo puede actuar como catalizador para atraer inversión extranjera y fortalecer la economía local, sostuvo Christian Borja Terán, presidente de Valores Casa de Bolsa, en el Summit de Forbes Paraguay realizado en diciembre.</p>
<p>Según Borja Terán, el país se propone duplicar su economía en una década, pasando de USD 45.000 millones a USD 90.000 millones. El ejecutivo señaló que la inversión extranjera directa creció 15% durante el año, con proyecciones de un incremento de entre 20% y 30% anual hacia adelante, y estimó que la transformación de distintos sectores productivos podría concretarse en un horizonte de tres a cinco años.</p>
<p>“El Grado de Inversión es la supercarretera que te va a llevar más rápido y con mayor comodidad hacia Paraguay 2.0”, afirmó, en referencia al proyecto de desarrollo público-privado que impulsa sectores con ventajas competitivas como el inmobiliario, la agricultura y la ganadería.</p>
<p>Borja Terán también planteó que la formalización empresarial y la solidez de la estructura corporativa son condiciones —a las que calificó como “peajes”— necesarias para acelerar el ingreso de capital extranjero: “mientras más formalizadas estén las empresas y más condiciones de seguridad brinde el país, más rápido y sostenido será el crecimiento económico”.</p>
<p>Entre los mecanismos de soporte para esa estrategia, mencionó el sistema de depósito centralizado de valores, que garantiza la custodia de las inversiones internacionales que ingresan al mercado paraguayo.</p>
<p><a href="https://www.forbes.com.py/summit/el-mercado-bursatil-motor-impulsa-inversion-publica-privada-n83629" target="_blank" rel="noopener">Nota original →</a></p>', (SELECT id FROM media WHERE ruta = 'assets/img/noticia-placeholder.svg'), 'summit', 'publicado', 1, '2025-12-20', 'Valores Casa de Bolsa'
WHERE NOT EXISTS (SELECT 1 FROM noticias WHERE slug = 'christian-borja-teran-el-grado-de-inversion-la-supercarretera-hacia-paraguay-2-0');

INSERT INTO noticias (titulo, slug, resumen, contenido, imagen_destacada_id, categoria, estado, visible_front, fecha_publicacion, autor)
SELECT 'Christian Borja: “El mercado de valores ha evolucionado de manera positiva”', 'christian-borja-el-mercado-de-valores-ha-evolucionado-de-manera-positiva', 'En entrevista con Revista Plus, el CEO de Valores Casa de Bolsa hizo un balance de 2025 y adelantó los ejes de la estrategia del grupo para 2026.', '<p><em>Fuente: Revista Plus, 9 de febrero de 2026</em></p>
<p>Christian Borja, CEO de Valores Casa de Bolsa, calificó a 2025 como “un año muy positivo y de inflexión” para la compañía, en una entrevista publicada por Revista Plus. Según el ejecutivo, el Grupo Valores se posicionó entre las 100 empresas con mayor patrimonio del país y registró un crecimiento cercano al 5%, lo que destacó especialmente al tratarse de “una de las pocas casas de bolsa fuera de grupos bancarios”.</p>
<p>Sobre el desempeño del mercado local, Borja afirmó: “El mercado de valores ha evolucionado de manera positiva en volumen, número de participantes y diversificación de productos”. Añadió que el crecimiento sostenido del volumen operado “evidencia que la bolsa aún tiene un alto potencial” de expansión.</p>
<p>El CEO describió el modelo de negocio de la firma como de “arquitectura abierta, enfocado en generar valor agregado real en las decisiones de inversión”.</p>
<p>De cara a 2026, Borja adelantó que la compañía buscará “consolidar la estrategia de boutique financiera”, con foco en bonos temáticos y en estructuras de financiamiento de entre USD 50 y USD 100 millones.</p>
<p>Borja es ecuatoriano, doctor en Derecho Financiero, cuenta con un MBA y reside en Paraguay desde hace 20 años.</p>
<p><a href="https://revistaplus.com.py/2026/02/09/christian-borja-el-mercado-de-valores-ha-evolucionado-de-manera-positiva/" target="_blank" rel="noopener">Nota original →</a></p>', (SELECT id FROM media WHERE ruta = 'assets/img/noticia-placeholder.svg'), 'mercado', 'publicado', 1, '2026-02-09', 'Valores Casa de Bolsa'
WHERE NOT EXISTS (SELECT 1 FROM noticias WHERE slug = 'christian-borja-el-mercado-de-valores-ha-evolucionado-de-manera-positiva');
